/* tslint:disable */
/* eslint-disable */
/**
 * Shift
 * Shift Server API documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordResponse
 */
export interface ForgotPasswordResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ForgotPasswordResponse
     */
    complete?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    emailMessage?: string;
    /**
     * 
     * @type {string}
     * @memberof ForgotPasswordResponse
     */
    msg?: string | null;
}

export function ForgotPasswordResponseFromJSON(json: any): ForgotPasswordResponse {
    return ForgotPasswordResponseFromJSONTyped(json, false);
}

export function ForgotPasswordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'complete': !exists(json, 'complete') ? undefined : json['complete'],
        'emailMessage': !exists(json, 'emailMessage') ? undefined : json['emailMessage'],
        'msg': !exists(json, 'msg') ? undefined : json['msg'],
    };
}

export function ForgotPasswordResponseToJSON(value?: ForgotPasswordResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'complete': value.complete,
        'emailMessage': value.emailMessage,
        'msg': value.msg,
    };
}


